### ISSUE TITLE
integrate support for SASS linting via webpack

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-frontend#116]
## Type of Change
- [ ] New Feature Request
- [ ] Improvement / Suggestion
- [ ] Bug
- [x] Other (please clarify below)

## Summary

Add support for linting / styleguide of SASS files in the application, akin to ESLint that is being used for JavaScript.

### TODO
- [ ] All Components linted / fixed
- [ ] All Views linted / fixed
- [ ] No "fail on error" when developing, "fail on error" on production build
